export const COMPLEXITY_VALUE = 'COMPLEXITY_VALUE';
export const CHANGE_GAME_STATE = 'CHANGE_GAME_STATE';
export const CHANGE_PLAYER = 'CHANGE_PLAYER';
export const WRITE_NEW_MESSAGE = 'WRITE_NEW_MESSAGE';
export const WINNER_STATUS = 'WINNER_STATUS';